(asm-target

 id: m6803

 byte-order: big-endian

 registers: ((a 0) (b 0) (x 0) (sp 0) (sr 0) (pc 0))

 register-sets: ((accu (a b))
		 (index (x)))

 addressing-modes: ((immediate (preceded-by* numeric (is #\#)))
		    (direct (preceded-by* numeric (is #\<)))
		    (indexed-null-offset
		     (preceded-by* (register 'index) (is #\,)))
		    (indexed-offset
		     (bind a-number (lambda (r)
				      (if (and (>= r -128) (<= r 127))
		    			  (result r)
		    			  fail)))))

 instructions:
 ((aba (0 (#x1b)))
  (abx (1 (((address 'immediate) (#x3a (lsb %op1))))))
  (adca (1 (((address 'immediate) (#x89 (lsb %op1)))
	    ((address 'direct) (#x99 (lsb %op1)))
	    ;; extended
	    (numeric (#xb9 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xa9 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xa9 (lsb %op1))))))))
  (adcb (1 (((address 'immediate) (#xc9 (lsb %op1)))
	    ((address 'direct) (#xd9 (lsb %op1)))
	    ;; extended
	    (numeric (#xf9 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xe9 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xe9 (lsb %op1))))))))
  (adda (1 (((address 'immediate) (#x8b (lsb %op1)))
	    ((address 'direct) (#x9b (lsb %op1)))
	    ;; extended
	    (numeric (#xbb (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xab #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xab (lsb %op1))))))))
  (addb (1 (((address 'immediate) (#xcb (lsb %op1)))
	    ((address 'direct) (#xdb (lsb %op1)))
	    ;; extended
	    (numeric (#xfb (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xeb #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xeb (lsb %op1))))))))
  (addd (1 (((address 'immediate) (#xc3 (msb %op1) (lsb %op1)))
	    ((address 'direct) (#xd3 (lsb %op1)))
	    ;; extended
	    (numeric (#xf3 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xe3 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xe3 (lsb %op1))))))))
  (anda (1 (((address 'immediate) (#x84 (lsb %op1)))
	    ((address 'direct) (#x94 (lsb %op1)))
	    ;; extended
	    (numeric (#xb4 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xa4 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xa4 (lsb %op1))))))))
  (andb (1 (((address 'immediate) (#xc4 (lsb %op1)))
	    ((address 'direct) (#xd4 (lsb %op1)))
	    ;; extended
	    (numeric (#xf4 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xe4 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xe4 (lsb %op1))))))))
  (asla (0 (#x48)))
  (aslb (0 (#x58)))
  (asld (0 (#x05)))
  (asl (1 (((address 'indexed-null-offset) (#x68 #x0))
	   (numeric (#x78 (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#x68 (lsb %op1))))))))
  (asra (0 (#x47)))
  (asrb (0 (#x57)))
  (asr (1 (((address 'indexed-null-offset) (#x67 #x0))
	   (numeric (#x77 (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#x67 (lsb %op1))))))))
  (bcc (1 (((signed-number-range 8) (#x24 %op1))
	   (numeric (#x24 (lsb (- %op1 (+ 2 current-origin))))))))
  (bcs (1 (((signed-number-range 8) (#x25 %op1))
	   (numeric (#x25 (lsb (- %op1 (+ 2 current-origin))))))))
  (beq (1 (((signed-number-range 8) (#x27 %op1))
	   (numeric (#x27 (lsb (- %op1 (+ 2 current-origin))))))))
  (bge (1 (((signed-number-range 8) (#x2c %op1))
	   (numeric (#x2c (lsb (- %op1 (+ 2 current-origin))))))))
  (bgt (1 (((signed-number-range 8) (#x2e %op1))
	   (numeric (#x2e (lsb (- %op1 (+ 2 current-origin))))))))
  (bhi (1 (((signed-number-range 8) (#x22 %op1))
	   (numeric (#x22 (lsb (- %op1 (+ 2 current-origin))))))))
  (bhs (1 (((signed-number-range 8) (#x24 %op1))
	   (numeric (#x24 (lsb (- %op1 (+ 2 current-origin))))))))
  (bita (1 (((address 'immediate) (#x85 (lsb %op1)))
	    ((address 'direct) (#x95 (lsb %op1)))
	    ;; extended
	    (numeric (#xb5 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xa5 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xa5 (lsb %op1))))))))
  (bitb (1 (((address 'immediate) (#xc5 (lsb %op1)))
	    ((address 'direct) (#xd5 (lsb %op1)))
	    ;; extended
	    (numeric (#xf5 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xe5 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xe5 (lsb %op1))))))))
  (ble (1 (((signed-number-range 8) (#x2f %op1))
	   (numeric (#x2f (lsb (- %op1 (+ 2 current-origin))))))))
  (blo (1 (((signed-number-range 8) (#x25 %op1))
	   (numeric (#x25 (lsb (- %op1 (+ 2 current-origin))))))))
  (bls (1 (((signed-number-range 8) (#x23 %op1))
	   (numeric (#x23 (lsb (- %op1 (+ 2 current-origin))))))))
  (blt (1 (((signed-number-range 8) (#x2d %op1))
	   (numeric (#x2d (lsb (- %op1 (+ 2 current-origin))))))))
  (bmi (1 (((signed-number-range 8) (#x2b %op1))
	   (numeric (#x2b (lsb (- %op1 (+ 2 current-origin))))))))
  (bne (1 (((signed-number-range 8) (#x26 %op1))
	   (numeric (#x26 (lsb (- %op1 (+ 2 current-origin))))))))
  (bpl (1 (((signed-number-range 8) (#x2a %op1))
	   (numeric (#x2a (lsb (- %op1 (+ 2 current-origin))))))))
  (bra (1 (((signed-number-range 8) (#x20 %op1))
	   (numeric (#x20 (lsb (- %op1 (+ 2 current-origin))))))))
  (brn (1 (((signed-number-range 8) (#x21 %op1))
	   (numeric (#x21 (lsb (- %op1 (+ 2 current-origin))))))))
  (bsr (1 (((signed-number-range 8) (#x8d %op1))
	   (numeric (#x8d (lsb (- %op1 (+ 2 current-origin))))))))
  (bvc (1 (((signed-number-range 8) (#x28 %op1))
	   (numeric (#x28 (lsb (- %op1 (+ 2 current-origin))))))))
  (bvs (1 (((signed-number-range 8) (#x29 %op1))
	   (numeric (#x29 (lsb (- %op1 (+ 2 current-origin))))))))
  (cba (0 (#x11)))
  (clc (0 (#x0c)))
  (cli (0 (#x0e)))
  (clra (0 (#x4f)))
  (clrb (0 (#x5f)))
  (clr (1 (((address 'indexed-null-offset) (#x6f #x0))
	   (numeric (#x7f (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#x6f (lsb %op1))))))))
  (cmpa (1 (((address 'immediate) (#x81 (lsb %op1)))
	    ((address 'direct) (#x91 (lsb %op1)))
	    ;; extended
	    (numeric (#xb1 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xa1 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xa1 (lsb %op1))))))))
  (cmpb (1 (((address 'immediate) (#xc1 (lsb %op1)))
	    ((address 'direct) (#xd1 (lsb %op1)))
	    ;; extended
	    (numeric (#xf1 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xe1 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xe1 (lsb %op1))))))))
  (coma (0 (#x43)))
  (comb (0 (#x53)))
  (com (1 (((address 'indexed-null-offset) (#x63 #x0))
	   (numeric (#x73 (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#x63 (lsb %op1))))))))
  (cpx (1 (((address 'direct) (#x9c (lsb %op1)))
	   ((address 'indexed-null-offset) (#xac #x0))
	   ((address 'immediate) (#x8c (msb %op1) (lsb %op1)))
	   (numeric (#xbc (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	     (((register 'index) (#xac (lsb %op1))))))))
  (daa (0 (#x19)))
  (deca (0 (#x4a)))
  (decb (0 (#x5a)))
  (dec (1 (((address 'indexed-null-offset) (#x6a #x0))
	   (numeric (#x7a (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#x6a (lsb %op1))))))))
  (des (0 (#x34)))
  (dex (0 (#x9)))
  (eora (1 (((address 'immediate) (#x88 (lsb %op1)))
	    ((address 'direct) (#x98 (lsb %op1)))
	    ;; extended
	    (numeric (#xb8 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xa8 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xa8 (lsb %op1))))))))
  (eorb (1 (((address 'immediate) (#xc8 (lsb %op1)))
	    ((address 'direct) (#xd8 (lsb %op1)))
	    ;; extended
	    (numeric (#xf8 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xe8 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xe8 (lsb %op1))))))))
  (hcf (0 (#xdd)))
  (inca (0 (#x4c)))
  (incb (0 (#x5c)))
  (inc (1 (((address 'indexed-null-offset) (#x6c #x0))
	   (numeric (#x7c (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#x6c (lsb %op1))))))))
  (ins (0 (#x31)))
  (inx (0 (#x8)))
  (jmp (1 (((address 'indexed-null-offset) (#x6e #x0))
	   (numeric (#x7e (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#x6e (lsb %op1))))))))
  (jsr (1 (((address 'direct) (#x9d (lsb %op1)))
	   ((address 'indexed-null-offset) (#xad #x0))
	   (numeric (#xbd (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#xad (lsb %op1))))))))
  (ldaa (1 (((address 'immediate) (#x86 (lsb %op1)))
	    ((address 'direct) (#x96 (lsb %op1)))
	    ;; extended
	    (numeric (#xb6 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xa6 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xa6 (lsb %op1))))))))
  (ldab (1 (((address 'immediate) (#xc6 (lsb %op1)))
	    ((address 'direct) (#xd6 (lsb %op1)))
	    ;; extended
	    (numeric (#xf6 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xe6 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xe6 (lsb %op1))))))))
  (ldd (1 (((address 'immediate) (#xcc (msb %op1) (lsb %op1)))
	   ((address 'direct) (#xdc (lsb %op1)))
	   ;; extended
	   (numeric (#xfc (msb %op1) (lsb %op1)))
	   ((address 'indexed-null-offset) (#xec #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xec (lsb %op1))))))))
  (lds (1 (((address 'direct) (#x9e (lsb %op1)))
	   ((address 'indexed-null-offset) (#xae #x0))
	   ((address 'immediate) (#x8e (msb %op1) (lsb %op1)))
	   (numeric (#xbe (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#xae (lsb %op1))))))))
  (ldx (1 (((address 'direct) (#xde (lsb %op1)))
	   ((address 'indexed-null-offset) (#xee #x0))
	   ((address 'immediate) (#xce (msb %op1) (lsb %op1)))
	   (numeric (#xfe (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	     (((register 'index) (#xee (lsb %op1))))))))
  (lsla (0 (#x48)))
  (lslb (0 (#x58)))
  (lsld (0 (#x05)))
  (lsl (1 (((address 'indexed-null-offset) (#x68 #x0))
	   (numeric (#x78 (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#x68 (lsb %op1))))))))
  (lsra (0 (#x44)))
  (lsrb (0 (#x54)))
  (lsrd (0 (#x04)))
  (lsr (1 (((address 'indexed-null-offset) (#x64 #x0))
	   (numeric (#x74 (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#x64 (lsb %op1))))))))
  (mul (0 (#x3d)))
  (nba (0 (#x14)))
  (nega (0 (#x40)))
  (negb (0 (#x50)))
  (neg (1 (((address 'indexed-null-offset) (#x60 #x0))
	   (numeric (#x70 (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#x60 (lsb %op1))))))))
  (nop (0 (#x1)))
  (ora (1 (((address 'immediate) (#x8a (lsb %op1)))
	   ((address 'direct) (#x9a (lsb %op1)))
	   ;; extended
	   (numeric (#xba (msb %op1) (lsb %op1)))
	   ((address 'indexed-null-offset) (#xaa #x0))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#xaa (lsb %op1))))))))
  (orb (1 (((address 'immediate) (#xca (lsb %op1)))
	   ((address 'direct) (#xda (lsb %op1)))
	   ;; extended
	   (numeric (#xfa (msb %op1) (lsb %op1)))
	   ((address 'indexed-null-offset) (#xea #x0))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#xea (lsb %op1))))))))
  (psha (0 (#x36)))
  (pshb (0 (#x37)))
  (pshx (0 (#x3c)))
  (pula (0 (#x32)))
  (pulb (0 (#x33)))
  (pulx (0 (#x38)))
  (rola (0 (#x49)))
  (rola (0 (#x49)))
  (rolb (0 (#x59)))
  (rol (1 (((address 'indexed-null-offset) (#x69 #x0))
	   (numeric (#x79 (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#x69 (lsb %op1))))))))
  (rora (0 (#x46)))
  (rorb (0 (#x56)))
  (ror (1 (((address 'indexed-null-offset) (#x66 #x0))
	   (numeric (#x76 (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#x66 (lsb %op1))))))))
  (rti (0 (#x3b)))
  (rts (0 (#x39)))
  (sba (0 (#x10)))
  (sbca (1 (((address 'immediate) (#x82 (lsb %op1)))
	    ((address 'direct) (#x92 (lsb %op1)))
	    ;; extended
	    (numeric (#xb2 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xa2 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xa2 (lsb %op1))))))))
  (sbcb (1 (((address 'immediate) (#xc2 (lsb %op1)))
	    ((address 'direct) (#xd2 (lsb %op1)))
	    ;; extended
	    (numeric (#xf2 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xe2 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xe2 (lsb %op1))))))))
  (sec (0 (#xd)))
  (sei (0 (#xf)))
  (sev (0 (#xb)))
  (staa (1 (((address 'immediate) (#x87 #x00 (lsb %op1)))
	    ((address 'direct) (#x97 (lsb %op1)))
	    ;; extended
	    (numeric (#xb7 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xa7 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xa7 (lsb %op1))))))))
  (stab (1 (((address 'immediate) (#xc7 #x00 (lsb %op1)))
	    ((address 'direct) (#xd7 (lsb %op1)))
	    ;; extended
	    (numeric (#xf7 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xe7 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xe7 (lsb %op1))))))))
  (std (1 (((address 'direct) (#xdd (lsb %op1)))
	   ;; extended
	   (numeric (#xfd (msb %op1) (lsb %op1)))
	   ((address 'indexed-null-offset) (#xed #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xed (lsb %op1))))))))
  (sts (1 (((address 'direct) (#x9f (lsb %op1)))
	   ((address 'indexed-null-offset) (#xaf #x0))
	   ((address 'immediate) (#x8f #x00 (msb %op1) (lsb %op1)))
	   (numeric (#xbf (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#xaf (lsb %op1))))))))
  (stx (1 (((address 'direct) (#xdf (lsb %op1)))
	   ((address 'indexed-null-offset) (#xef #x0))
	   ((address 'immediate) (#xcf #x00 (msb %op1) (lsb %op1)))
	   (numeric (#xff (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	     (((register 'index) (#xef (lsb %op1))))))))
  (suba (1 (((address 'immediate) (#x80 (lsb %op1)))
	    ((address 'direct) (#x90 (lsb %op1)))
	    ;; extended
	    (numeric (#xb0 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xa0 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xa0 (lsb %op1))))))))
  (subb (1 (((address 'immediate) (#xc0 (lsb %op1)))
	    ((address 'direct) (#xd0 (lsb %op1)))
	    ;; extended
	    (numeric (#xf0 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xe0 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xe0 (lsb %op1))))))))
  (subd (1 (((address 'immediate) (#x83 (msb %op1) (lsb %op1)))
	    ((address 'direct) (#x93 (lsb %op1)))
	    ;; extended
	    (numeric (#xb3 (msb %op1) (lsb %op1)))
	    ((address 'indexed-null-offset) (#xa3 #x0))))
	(2 (((address 'indexed-offset)
	     (((register 'index) (#xa3 (lsb %op1))))))))
  (swi (0 (#x3f)))
  (tab (0 (#x16)))
  (tap (0 (#x6)))
  (tba (0 (#x17)))
  (tpa (0 (#x7)))
  (tsta (0 (#x4d)))
  (tstb (0 (#x5d)))
  (tst (1 (((address 'indexed-null-offset) (#x6d #x0))
	   (numeric (#x7d (msb %op1) (lsb %op1)))))
       (2 (((address 'indexed-offset)
	    (((register 'index) (#x6d (lsb %op1))))))))
  (tsx (0 (#x30)))
  (txs (0 (#x35)))
  (wai (0 (#x3e)))))
